### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by dbgnu76** [dvdgeisler/DirigeraClient#52]
![dirigeraerror](https://user-images.githubusercontent.com/43219792/204526202-22db336a-6cf2-4dd9-8cd5-38fd11e3f224.PNG)

something i am doing wrong ?

**Comment by TheMrBooyah** [comment]
It says that the target release is invalid. This can happen due to a number of factors.
However, to make your life easier, we updated the readme.
To run the dump application, you no longer need to checkout and build the code yourself. Just navigate to the [releases](https://github.com/dvdgeisler/DirigeraClient/releases) page and download the [dump-application](https://github.com/dvdgeisler/DirigeraClient/releases/download/latest/dirigera-client-dump.jar) from the latest development build.

When you did that the only thing you need is the IP of your gateway and Java 17 or higher installed. ([See instructions](https://github.com/dvdgeisler/DirigeraClient#run-the-dump-application))

**Comment by dbgnu76** [comment]
Nice, all is working now :)
